modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License 3.0"
issueTrackerURL="https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues"

[[mods]]
modId="vehicle"
version="0.45.3"
displayName="MrCrayfish's Vehicle Mod"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=vehicle"
displayURL="https://mrcrayfish.com/mods?id=vehicle"
logoFile="vehicle_mod.png"
credits="Phylogeny https://github.com/Phylogeny Mo0dss https://github.com/Moodsss"
authors="MrCrayfish"
description="A mod that adds vehicles into Minecraft!"

[[dependencies.vehicle]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.54,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vehicle]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vehicle]]
    modId="framework"
    mandatory=true
    versionRange="[0.2.3,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.vehicle]]
    modId="posture"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"